### ISSUE TITLE
Cannot use this code in armhf architecture

### ISSUE THREAD

**Issue by finch185277** [Microsheep/D2-command-line-login#1]
Hello @Microsheep ,

Because this repository was compiled, I could not reuse this code in Raspberry Pi 3.
here is the error message:
```
-bash: ./standalone/login: cannot execute binary file: Exec format error
```

Would you like provide source code?

PS. 
Another solution to login dorm network is using `ssh -D <port number> <dest.>` 
to build ssh tunnel, and use the proxy in the browser to login the network (ex. SwitchyOmega).

Thanks.

**Comment by Microsheep** [comment]
Hi @finch185277 ~

This is a really old script. So I am not sure that this script will still work.
The source code is already in the repo as the file `login.py`
I think it is simple to understand and can be modified as needed.

The standalone version is produced using something like this
https://github.com/pyinstaller/pyinstaller
This is to prevent some users from not installing requests and bs4 before running it with cronjob

BTW. At that time, I had servers that does not have a graphical interface installed, so it is a hassle to rely on a proxy and a graphical interface to login. So this script is ran by a cron job periodically and keeps the servers connected.
